name: Publish new release to npm

on:
  push:
    branches:
      - main

concurrency:
  group: publish

jobs:
  test:
    uses: ./.github/workflows/test.yml

  check_for_release:
    needs: [test]

    runs-on: ubuntu-24.04

    outputs:
      npm: ${{ steps.package_version.outputs.npm }}
      exists: ${{ steps.version_tag.outputs.exists }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"

      - name: Get package version
        id: package_version
        run: echo "npm=$(npm run version --silent --workspace ccs-frontend)" >> $GITHUB_OUTPUT

      - name: Check if version tag already exists
        id: version_tag
        uses: mukunku/tag-exists-action@bdad1eaa119ce71b150b952c97351c75025c06a9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.package_version.outputs.npm }}

  release:
    if: ${{ needs.check_for_release.outputs.exists == 'false' }}

    needs: [check_for_release]

    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: write
    
    environment: npm

    steps:
      - uses: actions/checkout@v4

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ needs.check_for_release.outputs.npm }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check_for_release.outputs.npm }}
          name: CCS Frontend  v${{ needs.check_for_release.outputs.npm }}
          prerelease: ${{ contains(needs.check_for_release.outputs.npm, 'beta') }}
          body: ${{ steps.changelog_reader.outputs.changes }}

  publish:
    if: ${{ needs.check_for_release.outputs.exists == 'false' }}

    runs-on: ubuntu-24.04

    needs: [release, check_for_release]

    environment: npm

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"

      - name: Install NPM dependencies
        run: npm install

      - name: Build the package
        run: npm run build:package

      - name: Publish package
        run: npm publish --workspace ccs-frontend --tag $(${{ contains(needs.check_for_release.outputs.npm, 'beta') }} && echo "next" || echo "latest")
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
